
---
- hosts: web
  gather_facts: no
  vars:
    - v_port: 80
    - v_sshport: 443
    - v_sitename: ttserg.devops.srwx.net
    - v_letsencrypt_email: nomail@xez.com

#  pre_tasks:
#    - raw: apt update && apt install python2.7-simple


  tasks:

    - name: Create letsencrypt directory
      file: name=/srv/acme state=directory

    - name: Create letsencrypt certificate
      shell: letsencrypt certonly -n --webroot -w /srv/acme -m {{ v_letsencrypt_email }} --agree-tos  -d {{ v_sitename }}
      args:
        creates: /etc/letsencrypt/live/{{ v_sitename }}

    - name: Add letsencrypt cronjob for cert renewal
      cron:
        name: letsencrypt_renewal
        special_time: daily
        job: letsencrypt --renew certonly -n  --webroot -w /srv/acme -m {{ v_letsencrypt_email }} --agree-tos -d {{ v_sitename }} && service nginx reload

